// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Para SQLite y el adaptador de LibSQL en producción, Prisma requiere un formato de URL SQLite válido
    // como 'file:./dev.db' para pasar la validación interna, aunque la conexión real se haga a través del adaptador.
    url: process.env["DATABASE_URL"] && process.env["DATABASE_URL"].startsWith("file:")
      ? process.env["DATABASE_URL"]
      : "file:./dev.db",
  },
});
